arena-manager: much much much better .cvs-git approach

diff --git a/arena-manager b/arena-manager
--- a/arena-manager
+++ b/arena-manager
@@ -197,38 +197,41 @@ update)
                 $GIT svn rebase
                 es=$?
             elif test "$rd" != ${rd/.cvs-bombgit}; then
-                $GIT co remotes/origin/master
+                $GIT checkout remotes/origin/master
                 $CVS update -ARPd #C
                 es=$?
-                $GIT add --all && $GIT ci -m 'arena-manager .cvs-bombgit update'
-                $GIT co master
+                $GIT add --all &&
+                $GIT commit -m 'arena-manager .cvs-bombgit update'
+                $GIT checkout master
             elif test "$rd" != ${rd/.cvs-git}; then
-                ldir='.git/.cvsps'
-                tar xjf "$ldir.tbz" || {
-                    echo >&2 "$rd: bail: tar xjf $ldir.tbz"
-                    exit 11
+                cvsps_dir="$HOME/.cvsps"
+                test -d "$cvsps_dir" || mkdir "$cvsps_dir" || {
+                    echo >&2 "$rd: failed to create $cvsps_dir directory"
+                    exit 10
                 }
-                cp -f "$ldir.tbz" "$ldir.tbz.last"
-                hdir="$HOME/.cvsps"
-                test -d "$hdir" || mkdir "$hdir" || {
-                    echo >&2 "$rd: failed to create $hdir directory"
-                    exit 12
-                }
-                root="$ldir/CVSROOT"
-                repo="$ldir/MODULE"
-                cache=$(<$ldir/CVSPS_FILE)
-                mv -f "$ldir/cvs-revisions" .git/
-                mv -f "$ldir/$cache" "$hdir/$cache"
-                $GIT cvsimport -aR -r origin -p '-u,--cvs-direct' \
-                     -d $(<$root) $(<$repo)
+
+                $GIT checkout -f arena-manager-config || exit 11
+                master=$(<git_master)           # The name of the master branch
+                cvs_root=$(<cvs_root)           # CVSROOT repo URL (CVS/Root)
+                cvs_module=$(<cvs_module)       # CVS module (CVS/Repository)
+                cvsps_file=$(<cvsps_file)       # cvsps(1) cache file name
+                test -f cvs-revisions && Rflag=-R || Rflag= # git cvsimport dat
+
+                test x"$Rflag" != x && cp -f cvs-revisions .git/
+                cp -f cvsps_cache "$cvsps_dir/$cvsps_file"
+                $GIT cvsimport -ai $Rflag -p '-u,--cvs-direct' \
+                     -r origin -d "$cvs_root" "$cvs_module"
                 es=$?
-                mv -f .git/cvs-revisions "$ldir/"
-                mv -f "$hdir/$cache" "$ldir/$cache"
-                tar cjf "$ldir.tbz" "$ldir" || {
-                    echo >&2 "$rd: bail: tar cjf $ldir.tbz $ldir"
-                    exit 13
+                test $es -ne 0 && {
+                    echo >&2 "$rd git(1) cvsimport failed, bailing out"
+                    $GIT checkout -f $master
+                    exit $es
                 }
-                rm -rf $ldir
+                test x"$Rflag" != x && mv -f .git/cvs-revisions .
+                mv -f "$cvsps_dir/$cvsps_file" cvsps_cache
+
+                $GIT commit -am 'arena-manager .cvs-git update' || exit 12
+                $GIT checkout $master || exit 13
             elif test "$rd" != ${rd/.hg}; then
                 $HG -v pull #-u
                 es=$?
