arena-manager: move/require ARENA variable to/from environment

diff --git a/arena-manager b/arena-manager
--- a/arena-manager
+++ b/arena-manager
@@ -33,9 +33,6 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Top dir where everything happens
-ARENA="$HOME/arena/code.extern"
-
 # And the version control executables
 GIT=git
 HG=hg
@@ -567,8 +564,13 @@ checkup() {
 
 ## exec
 
+# Top dir where everything happens
+if test x"$ARENA" = x; then
+    echo >&2 "(Environment) variable ARENA is not set"
+    exit 1
+fi
 cd $ARENA || {
-    echo >&2 "Failed to chdir to $ARENA"
+    echo >&2 "Failed to chdir to ARENA=$ARENA"
     exit 1
 }
 
