Copyright 2021, and we now use gitweb not cgit

diff --git a/gen-uushar-wrapper b/gen-uushar-wrapper
--- a/gen-uushar-wrapper
+++ b/gen-uushar-wrapper
@@ -5,11 +5,9 @@
 #@ Execute it (the generated archive) to invoke any of the programs contained
 #@ therein.  On the first run with arguments, the wrapper will create a hidden
 #@ directory in your $TMPDIR to unpack the archive therein; without arguments
-#@ it'll always print creation time and members shipped.
-#@ Web: https://www.sdaoden.eu/code.html
-#@ Git: https?://git.sdaoden.eu/cgit/s-toolbox.git
+#@ it will always print creation time and members shipped.
 #
-# Copyright (c) 2012 - 2016 Steffen (Daode) Nurpmeso <steffen@sdaoden.eu>.
+# Copyright (c) 2012 - 2021 Steffen Nurpmeso <steffen@sdaoden.eu>.
 #
 # Permission to use, copy, modify, and/or distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -42,7 +40,7 @@ if [ -f "${SHAR}" ]; then
    exit 1
 fi
 
-printf "Yay, it'll be \`${SHAR}'.\n\n%s\n%s\n%s" \
+printf "Yay, it will be \`${SHAR}'.\n\n%s\n%s\n%s" \
    "The special command \`+' should map to a subcommand?" \
    "(As in: '\$ ${SHAR} + -h' -> '\$ SUBCOMMAND -h')?" \
    'Enter desired command or the empty string otherwise [] '
@@ -128,13 +126,13 @@ CREATION_DATE=`date -u`
 cat <<\! > "${SHAR}"
 #!/bin/sh -
 #@ This file has been created by gen-uushar-wrapper, which is
-# Copyright (c) 2012 - 2016 Steffen (Daode) Nurpmeso <steffen@sdaoden.eu>.
+# Copyright (c) 2012 - 2021 Steffen Nurpmeso <steffen@sdaoden.eu>.
 #@ by means of the ISC license.
 #@ It contains a shell-archive-execution-environment.
 #@ Run it, and it will tell you which executable files it contains.
-#@ Run it with the name of such an executable, and it'll create a hidden
-#@ directory in your $TMPDIR to expand the shipped executables.
-#@ From then on, it'll redirect it's invocations to those programs.
+#@ Run it with the name of such an executable, and it will create a
+#@ hidden directory in your $TMPDIR to expand the shipped executables.
+#@ From then on, it will redirect its invocations to those programs.
 #
 #@ Archives produced using this implementation of gen-uushar-wrapper
 #@ may be easily examined with the command:
@@ -142,7 +140,7 @@ cat <<\! > "${SHAR}"
 #
 !
 
-# It's indeed our $SHAR
+# Its indeed our $SHAR
 trap "rm -rf '${SHAR}'" 0
 
 # A shell archive is not a transparent thing either!
@@ -173,12 +171,12 @@ if [ -d "${i}" ]; then
 fi
 #
 printf "%s\n%s\n" "The directory \`${i}'" \
-   "doesn't exist: creating it and expanding this archive first"
+   "does not exist: creating it and expanding this archive first"
 MYSELF="`pwd`/${0}"
-[ ${?} -ne 0 ] && { echo >&2 "Can't detect current working directory"; exit 1; }
-mkdir -p "${i}" || { echo >&2 "Can't create directory \`${i}'"; exit 1; }
+[ ${?} -ne 0 ] && { echo >&2 "Cannot detect current directory"; exit 1; }
+mkdir -p "${i}" || { echo >&2 "Cannot create directory \`${i}'"; exit 1; }
 cd "${i}" ||
-   { echo >&2 "Can't cd into \`${i}', removing it"; rm -rf "${i}"; exit 1; }
+   { echo >&2 "Cannot cd into \`${i}', removing it"; rm -rf "${i}"; exit 1; }
 #
 !
 
@@ -193,7 +191,8 @@ do
    echo >> "${SHAR}" "echo 'X - ${bi}'"
    if [ -z "${cfun}" ]; then
       echo >> "${SHAR}" \
-         "sed 's/^X//' << \! | uudecode -o /dev/stdout > \"${bi}\"; chmod 0755 \"${bi}\""
+         "sed 's/^X//' << \! |\
+            uudecode -o /dev/stdout > \"${bi}\"; chmod 0755 \"${bi}\""
       < "${i}" uuencode -m /dev/stdout | sed 's/^/X/' >> "${SHAR}"
    else
       echo >> "${SHAR}" \
