gen-uushar-wrapper: ISC license, ARGV enable..
Rethought it a bit and it turned out to be stupid.
First of all, let's use the ISC license, as i'm currently
turning over all my work to it.

Then enable the possibility to specify the commands which should
make up the archive on the command line, thus allow
tab-completion.

Also pimp the output that is produced and group it a bit in
blocks.

Introduce the produced file with a TOC of all programs which are
contained, just like (uu)shar(1) does.

And finally, get rid of the functions, unroll all the code in
the archive file, since it's only a few lines anyway.
While at it, drop support for real execution of a command the
first time an archive is executed, since sh(1) doesn't support
goto:, and there is no more function to call.

The good news on the latter: well, arguments should now be
passed through to the actual command unchanged and thus as
desired.  Au.

diff --git a/gen-uushar-wrapper b/gen-uushar-wrapper
--- a/gen-uushar-wrapper
+++ b/gen-uushar-wrapper
@@ -1,47 +1,34 @@
 #!/bin/sh
 #@ gen-uushar-wrapper creates a shar(1)-like shell archive (but with
-#@ uuencode(1)d content) of given files, that is executable.
+#@ uuencode(1)d content) of given files (read from STDIN and/or ARGV), that is
+#@ itself executable.
 #@ Execute it (the generated archive) to invoke any of the programs contained
 #@ therein.  On the first run, the wrapper will create a hidden directory in
-#@ your $TMPDIR to unpack the archive therein.
+#@ your $TMPDIR to unpack the archive therein.
 #
 # Copyright (c) 2012 Steffen Daode Nurpmeso <sdaoden@users.sf.net>.
-# All rights reserved.
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
+# Permission to use, copy, modify, and/or distribute this software for any
+# purpose with or without fee is hereby granted, provided that the above
+# copyright notice and this permission notice appear in all copies.
 #
-# 1. Redistributions of source code must retain the above copyright notice,
-#    this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright notice,
-#    this list of conditions and the following disclaimer in the documentation
-#    and/or other materials provided with the distribution.
-# 3. Neither the name of the author nor the names of its contributors
-#    may be used to endorse or promote products derived from this software
-#    without specific prior written permission.
-#
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
-# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
-# PURPOSE ARE DISCLAIMED.
-# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
-# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
-# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
+# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
+# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
+# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
+# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
+# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
 ##  --  >8  --  8<  --  ##
-cat <<-EOT
-   Howdy howdy, jo-ho hooo!
-   So let's create an uuencoded shell archive of the utilities you specify.
-   Please answer the upcoming questions for this to work.
-   You can at any time interrupt with CTRL-C.
+ARGS=$@
 
-EOT
-
-printf "What should be the name of the wrapper: "
+printf "%s\n%s\n%s\n%s\n\n%s " \
+	'Howdy howdy, jo-ho hooo!' \
+	'So let us create an uuencoded shell archive of the given utilities.' \
+	'Please answer the upcoming questions for this to work.' \
+	'You can at any time interrupt with CTRL-C.' \
+   'What should be the name of the wrapper:'
 read CREATOR_PROG
 if [ -f "$CREATOR_PROG.sh" ]; then
    echo >&2 "$CREATOR_PROG.sh already exists, bailing out."
@@ -52,7 +39,7 @@ elif [ x"$CREATOR_PROG" == x ]; then
 fi
 CREATOR_PROG="$CREATOR_PROG.sh"
 
-printf "Yay, it'll be $CREATOR_PROG.\n%s\n%s [] " \
+printf "Yay, it'll be $CREATOR_PROG.\n\n%s\n%s [] " \
    "Is there any subcommand which should be called for '+'?" \
    "(As in: <$CREATOR_PROG + -arg1 -arg2> -> <XXX -arg1 -arg2>)?"
 read CREATOR_DEFEXEC
@@ -61,90 +48,75 @@ printf "\n%s\n%s\n%s\n\t- " \
    "So, we'll then enter a loop to read the programs to include." \
    "Please note that the command may not contain an AT sign (@)." \
    "Please terminate your input by giving an empty line."
-
 PROGS=
+[ ${#ARGS} -ne 0 ] && set -- $ARGS
 while :; do
-   read i
-   [ x"$i" == x ] && break
+   [ ${#ARGS} -ne 0 ] && \
+      { i=$1; shift || break; :; } || \
+      { read i; [ x"$i" == x ] && break; :; }
    if [ ! -x "$i" ]; then
       echo >&2 "$i does not exist or is not executable, bailing out."
       exit 1
    fi
-   printf "$i: ok\n\t - "
+   printf "$i: ok\n\t- "
    [ x"$PROGS" == x ] && PROGS=$i || PROGS="$PROGS@$i"
 done
 
+# Everything get.set.go, so write the actual shell archive
+set -C
+printf ".. end of list\nFine, so i'm doing my work now\n"
 trap "rm -rf '$CREATOR_PROG'" 0
 
-
-set -C
+# Header
 cat <<\! > "$CREATOR_PROG"
 #!/bin/sh
-#@ This file was automatically created by gen-uushar-wrapper, which is
+#@ This file was automatically created by gen-uushar-wrapper, which is
 # Copyright (c) 2012 Steffen Daode Nurpmeso <sdaoden@users.sf.net>.
-# All rights reserved.
-#@ under the new 3-clause BSD license.
+#@ by means of the ISC license.
 
+# The following executable files are contained in here (basename(1)d):
 !
 
-printf "PROG=\"${CREATOR_PROG%.sh}\"\nDEFEXEC=\"$CREATOR_DEFEXEC\"\n" \
+oifs=$IFS
+IFS=@
+set -- $PROGS
+IFS=$oifs
+for i; do
+   printf "# - $i\n" >> "$CREATOR_PROG"
+done
+
+# A shell archive is not a transparent thing either!
+printf "\nPROG=\"${CREATOR_PROG%.sh}\"\nDEFEXEC=\"$CREATOR_DEFEXEC\"\n" \
    >> "$CREATOR_PROG"
 cat <<\! >> "$CREATOR_PROG"
-
 MYDIR=".$PROG"
-WWD=
-ARGS=$@
 
-runner() {
+[ -d "$TMPDIR/$MYDIR" ] && {
    PATH="$TMPDIR/$MYDIR:$PATH"
-   set -- $ARGS
-   if [ x"$DEFEXEC" != x ]; then
-      [ x"$1" == 'x+' ] && { shift; set -- "$DEFEXEC" $@; }
-   fi
-   if [ ! -x "$1" ]; then
-      echo >&2 "Sorry, but this archive did not contain '$1', bailing out"
+   [ x"$1" == 'x+' ] && { shift; :; } || { DEFEXEC=$1; shift; }
+   if [ ! -x "$DEFEXEC" ]; then
+      echo >&2 "Sorry, this archive has no program '$DEFEXEC', bailing out"
       exit 54
    fi
-   exec $@
-   echo >&2 "Failed to execute <$ARGS>"
+   exec "$DEFEXEC" "$@"
+   echo >&2 "Failed to execute <$DEFEXEC $@>"
    exit 1
 }
 
-pre_explode() {
-   cat <<%
-The directory
-	$TMPDIR/$MYDIR
-does not exist, creating it first, and exploding this shell archive.
-%
-
-   mkdir -p "$TMPDIR/$MYDIR" || {
-      echo >&2 "Cannot create '$TMPDIR/$MYDIR' directory"
-      exit 1
-   }
-
-   WWD=$(pwd)
-   cd "$TMPDIR/$MYDIR" || {
-      echo >&2 "Cannot enter $TMPDIR/$MYDIR to explode shell archive"
-      exit 1
-   }
+printf "The directory\n\t$TMPDIR/$MYDIR\n%s\n" \
+   'does not exist, creating it first, and exploding this shell archive.'
+mkdir -p "$TMPDIR/$MYDIR" || {
+   echo >&2 "Cannot create '$TMPDIR/$MYDIR' directory"
+   exit 1
+}
+cd "$TMPDIR/$MYDIR" || {
+   echo >&2 "Cannot enter $TMPDIR/$MYDIR to explode shell archive"
+   exit 1
 }
 
-post_explode() {
-   echo Shell archive exploded, now running command..
-   cd "$WWD" || {
-      echo >&2 "Cannot reenter starting working directory '$WWD'"
-      exit 1
-   }
-   runner
-   exit 55
-}
-
-[ -d "$TMPDIR/$MYDIR" ] && runner
-
-pre_explode
 !
 
-# 
+# uuencode(1)d the programs to embed
 oifs=$IFS
 IFS=@
 set -- $PROGS
@@ -157,9 +129,12 @@ for i; do
    printf "!\n# END of '$ uuencode -m $i $basei'\n" >> "$CREATOR_PROG"
 done
 
-echo post_explode >> "$CREATOR_PROG"
+printf "\necho '%s'\nexit 0\n" \
+      'Shell archive exploded, please rerun the command, now for real..' \
+   >> "$CREATOR_PROG"
 
+# The end
 chmod 0755 "$CREATOR_PROG"
-trap "" 0
+trap - 0
 exit 0
 # vim:set fenc=utf-8 filetype=sh syntax=sh ts=3 sts=3 sw=3 et tw=79:
