pam_shrundir: fix lockfile race; use fd approach

diff --git a/pam_shrundir b/pam_shrundir
--- a/pam_shrundir
+++ b/pam_shrundir
@@ -35,41 +35,45 @@ user=`id -u ${PAM_USER}`
 group=`id -g ${PAM_USER}`
 umask 0077
 
-touch "${lckfile}"
-flock "${lckfile}" -c '
+(
+   flock 8 || exit 10
    ex=0
-   if [ "'"${PAM_TYPE}"'" = open_session ]; then
-      if [ -d '"${user}"' ]; then :; else
-         mkdir -m 0700 '"${user}"' || exit 5
-         chown '"${user}"':'"${group}"' '"${user}"' || exit 6
-         echo 0 > '"${user}"'/'"${datfile}"'
-         chmod 0600 '"${user}"'/'"${datfile}"'
+   if [ "${PAM_TYPE}" = open_session ]; then
+      if [ -d "${user}" ]; then :; else
+         mkdir -m 0700 "${user}" || exit 5
+         chown "${user}":"${group}" "${user}" || exit 6
+         echo 0 > "${user}"/"${datfile}"
+         chmod 0600 "${user}"/"${datfile}"
       fi
       op=+
    else
       op=-
    fi
 
-   read cnt < '"${user}"'/'"${datfile}"'
+   read cnt < "${user}"/"${datfile}"
    [ -z "${cnt}" ] && cnt=0
    cnt=`expr ${cnt} ${op} 1`
    if [ ${cnt} -le 0 ]; then
-      rm -rf '"${user}"' || ex=7
+      rm -rf "${user}" || ex=7
    else
-      echo ${cnt} > '"${user}"'/'"${datfile}"'
+      echo ${cnt} > "${user}"/"${datfile}"
    fi
 
    exit ${ex}
-'
+) 8>"${lckfile}"
 e=${?}
 rm -f "${lckfile}"
 
+em=
 case ${e} in
-*) ;;
-5) logger -t pam_rundir 'ERROR: cannot create /run/user/'${user};;
-6) logger -t pam_rundir 'ERROR: cannot impersonate /run/user/'${user};;
-7) logger -t pam_rundir 'ERROR: cannot remove /run/user/'${user};;
+0) ;;
+5) em='cannot create /run/user/'${user};;
+6) em='cannot impersonate /run/user/'${user};;
+7) em='cannot remove /run/user/'${user};;
+10) em='cannot flock(1) '${lckfile};;
+*) em='unsorted flock(1) error';;
 esac
+[ -n "${em}" ] && logger -t pam_rundir 'ERROR: '"${em}"
 
 exit ${e}
 # s-sh-mode
